"use client";

import { AdminPlatformShell } from "@/components/admin-platform-shell";
import { createLeadActivity, nextPendingFollowUp, normalizeLead, normalizeLeadMobile } from "@/lib/lead-utils";
import { detectLeadRisk } from "@/lib/crm-workflow";
import { hydrateLiveState, LIVE_STATE_STORAGE_KEYS, readLocalArray, saveLiveState } from "@/lib/live-state";
import type { Lead, LeadFollowUp, LeadPriority, LeadStage } from "@/lib/types";
import { ArrowLeft, Building2, CalendarClock, Check, CircleDollarSign, Clock3, Mail, MapPin, MessageCircle, Phone, Save, ShieldAlert, Target, UserRound, X } from "lucide-react";
import { use, useEffect, useMemo, useState } from "react";

type SessionRow={participant_id:string;session_id:string;session_name:string;session_date:string;pre_score?:number;session_score?:number;total_score?:number;calculated_tier?:string;instant_signal?:string;scorecard_version?:string;scored_at?:string;meeting_id?:string;meeting_at?:string;meeting_owner?:string};
type ServerActivity={id:string;type:string;actor_user:string;body:string;created_at:string};
const stages:LeadStage[]=["New Leads","Contacted","Qualified","Proposal","Won","Lost"];
const lostReasons=["Price","No Budget","Timing","Partner Objection","Not Interested","Competitor","No Response","Wrong Fit","Other"];
const taskTypes:LeadFollowUp["type"][]=["Call","WhatsApp","Meeting","Send Information","Partner Call","Payment Follow-up"];
const inputClass="w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-bold outline-none";

export default function Lead360Page({params}:{params:Promise<{id:string}>}){
  const {id}=use(params);const [leads,setLeads]=useState<Lead[]>([]);const [loaded,setLoaded]=useState(false);const [sessions,setSessions]=useState<SessionRow[]>([]);const [serverActivities,setServerActivities]=useState<ServerActivity[]>([]);const [message,setMessage]=useState("");const [note,setNote]=useState("");const [taskType,setTaskType]=useState<LeadFollowUp["type"]>("Call");const [taskAt,setTaskAt]=useState("");const [taskNote,setTaskNote]=useState("");
  useEffect(()=>{const load=()=>{setLeads(readLocalArray<unknown>(LIVE_STATE_STORAGE_KEYS.leads).map(normalizeLead));setLoaded(true)};load();void hydrateLiveState().then(load);void fetch(`/api/crm/sales-sessions?leadId=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async(r)=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(ok){setSessions(data.participants??[]);setServerActivities(data.activities??[])}}).catch(()=>undefined)},[id]);
  const lead=leads.find((item)=>item.id===id);const risk=lead?detectLeadRisk(lead):null;
  const timeline=useMemo(()=>{if(!lead)return [];return [...(lead.activities??[]).map((a)=>({id:a.id,type:a.type,body:a.message,actor:a.createdBy||"Admin",createdAt:a.createdAt})),...serverActivities.map((a)=>({id:a.id,type:a.type,body:a.body,actor:a.actor_user,createdAt:a.created_at}))].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())},[lead,serverActivities]);
  async function update(patch:Partial<Lead>,activity?:{type:Parameters<typeof createLeadActivity>[0];message:string}){if(!lead)return;const now=new Date().toISOString();const next=leads.map((item)=>item.id===lead.id?normalizeLead({...item,...patch,lastActivityAt:activity?now:item.lastActivityAt,updatedAt:now,activities:activity?[createLeadActivity(activity.type,activity.message),...(item.activities??[])]:item.activities}):item);setLeads(next);await saveLiveState({leads:next})}
  async function addTask(){if(!lead||!taskAt){setMessage("Select next action date and time.");return}const dueAt=new Date(taskAt).toISOString();const task:LeadFollowUp={id:`followup-${Date.now().toString(36)}`,type:taskType,dueAt,note:taskNote.trim(),completed:false,createdAt:new Date().toISOString()};await update({followUps:[task,...(lead.followUps??[])],nextFollowUp:dueAt},{type:"follow_up",message:`${taskType} scheduled for ${formatDate(dueAt)}.`});setTaskAt("");setTaskNote("");setMessage("Next action scheduled.")}
  async function completeTask(taskId:string){if(!lead)return;const followUps=(lead.followUps??[]).map((item)=>item.id===taskId?{...item,completed:true,completedAt:new Date().toISOString()}:item);await update({followUps,nextFollowUp:nextPendingFollowUp(followUps)?.dueAt??""},{type:"follow_up",message:"Next action completed."})}
  async function addNote(){if(!lead||!note.trim())return;await update({notes:[note.trim(),...(lead.notes??[])]},{type:"note",message:note.trim()});setNote("");setMessage("Note added.")}
  if(!loaded)return <AdminPlatformShell activeLabel="Lead 360" title="Lead Profile"><div className="h-80 animate-pulse rounded-2xl bg-white"/></AdminPlatformShell>;
  if(!lead)return <AdminPlatformShell activeLabel="Lead 360" title="Lead Profile"><div className="grid min-h-96 place-items-center text-center"><div><p className="text-xl font-black">Lead not found</p><a className="mt-3 inline-flex text-sm font-black text-emerald-700" href="/lead-management">Back to leads</a></div></div></AdminPlatformShell>;
  const latest=sessions.find((row)=>row.total_score!==null&&row.total_score!==undefined);const activeTasks=(lead.followUps??[]).filter((item)=>!item.completed).sort((a,b)=>new Date(a.dueAt).getTime()-new Date(b.dueAt).getTime());
  return <AdminPlatformShell activeLabel="Lead 360" description="Complete lead context, score, next action and activity history." title={lead.name}>
    <a className="mb-4 inline-flex items-center gap-2 text-sm font-black text-slate-500 hover:text-slate-950" href="/lead-management"><ArrowLeft className="size-4"/>Back to leads</a>
    {message?<div className="mb-4 flex items-center justify-between rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700"><span>{message}</span><button onClick={()=>setMessage("")} type="button"><X className="size-4"/></button></div>:null}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><Badge text={lead.priority??"Warm"} tone={lead.priority==="Hot"?"rose":lead.priority==="Cold"?"sky":"amber"}/><Badge text={lead.stage} tone="slate"/>{risk?<Badge text={risk.replaceAll("_"," ")} tone="rose"/>:null}</div><h2 className="mt-4 text-3xl font-black">{lead.name}</h2><div className="mt-2 flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold text-slate-500"><span className="inline-flex items-center gap-1.5"><Phone className="size-4"/>{formatMobile(lead.mobile)}</span>{lead.email?<span className="inline-flex items-center gap-1.5"><Mail className="size-4"/>{lead.email}</span>:null}{lead.city?<span className="inline-flex items-center gap-1.5"><MapPin className="size-4"/>{lead.city}</span>:null}</div></div><div className="flex gap-2"><a className="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-4 py-3 text-sm font-black text-white" href={`tel:+91${normalizeLeadMobile(lead.mobile)}`}><Phone className="size-4"/>Call</a><a className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white" href={`https://wa.me/91${normalizeLeadMobile(lead.mobile)}`} target="_blank"><MessageCircle className="size-4"/>WhatsApp</a></div></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">Overview</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Info icon={Building2} label="Business / Interest" value={lead.interest||"Not provided"}/><Info icon={Target} label="Source" value={lead.source}/><Info icon={UserRound} label="Assigned counselor" value={lead.assignedTo||"Unassigned"}/><Info icon={CircleDollarSign} label="Potential value" value={`INR ${lead.revenuePotential.toLocaleString("en-IN")}`}/></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs font-black uppercase text-slate-500">Stage<select className={`${inputClass} mt-2`} onChange={(e)=>void update({stage:e.target.value as LeadStage},{type:"stage",message:`Stage changed from ${lead.stage} to ${e.target.value}.`})} value={lead.stage}>{stages.map((v)=><option key={v}>{v}</option>)}</select></label><label className="text-xs font-black uppercase text-slate-500">Priority<select className={`${inputClass} mt-2`} onChange={(e)=>void update({priority:e.target.value as LeadPriority})} value={lead.priority}>{["Hot","Warm","Cold"].map((v)=><option key={v}>{v}</option>)}</select></label>{lead.stage==="Lost"?<label className="text-xs font-black uppercase text-slate-500">Lost reason<select className={`${inputClass} mt-2`} onChange={(e)=>void update({lostReason:e.target.value},{type:"stage",message:`Lost reason: ${e.target.value}.`})} value={lead.lostReason||""}><option value="">Select required reason</option>{lostReasons.map((v)=><option key={v}>{v}</option>)}</select></label>:null}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-lg font-black">Session scorecard</h3><p className="mt-1 text-sm font-semibold text-slate-500">Server-validated historical snapshots.</p></div><a className="text-sm font-black text-emerald-700" href="/crm/sessions">Sessions</a></div>{latest?<div className="mt-4"><div className="rounded-xl bg-slate-950 p-4 text-white"><div className="flex items-end justify-between"><div><p className="text-xs font-black text-slate-400">LATEST SCORE</p><p className="mt-1 text-3xl font-black">{latest.total_score}/100</p></div><span className="rounded-lg bg-white px-3 py-2 text-sm font-black text-slate-950">Tier {latest.calculated_tier}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Score label="Pre score" value={`${latest.pre_score}/50`}/><Score label="Session score" value={`${latest.session_score}/50`}/></div></div><div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200">{sessions.map((row)=><div className="flex flex-wrap items-center justify-between gap-2 p-3" key={row.participant_id}><div><p className="text-sm font-black">{row.session_name}</p><p className="mt-1 text-xs font-semibold text-slate-500">{formatDay(row.session_date)} · {row.scorecard_version||"Not scored"}</p></div><div className="text-right"><p className="font-black">{row.total_score??"—"}/100</p>{row.meeting_at?<p className="text-xs font-bold text-emerald-700">Meeting {formatDate(row.meeting_at)}</p>:null}</div></div>)}</div></div>:<div className="mt-4 rounded-xl border border-dashed border-slate-300 p-6 text-center"><p className="font-black">No session score yet</p><p className="mt-1 text-sm font-semibold text-slate-500">Add this lead to a sales session to begin scoring.</p></div>}</section>
      </div>
      <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">Next action</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><select className={inputClass} onChange={(e)=>setTaskType(e.target.value as LeadFollowUp["type"])} value={taskType}>{taskTypes.map((v)=><option key={v}>{v}</option>)}</select><input className={inputClass} onChange={(e)=>setTaskAt(e.target.value)} type="datetime-local" value={taskAt}/><input className={`${inputClass} sm:col-span-2`} onChange={(e)=>setTaskNote(e.target.value)} placeholder="Purpose / context" value={taskNote}/><button className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white sm:col-span-2" onClick={()=>void addTask()} type="button">Schedule next action</button></div><div className="mt-4 divide-y divide-slate-100 rounded-xl border border-slate-200">{activeTasks.map((task)=><div className="flex items-center justify-between gap-3 p-3" key={task.id}><div><p className={`text-sm font-black ${new Date(task.dueAt)<new Date()?"text-rose-600":""}`}>{task.type} · {formatDate(task.dueAt)}</p>{task.note?<p className="mt-1 text-xs font-semibold text-slate-500">{task.note}</p>:null}</div><button className="grid size-9 place-items-center rounded-lg bg-emerald-50 text-emerald-700" onClick={()=>void completeTask(task.id)} type="button"><Check className="size-4"/></button></div>)}{!activeTasks.length?<p className="p-4 text-center text-sm font-bold text-amber-700">No next action—schedule one above.</p>:null}</div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">Add note</h3><textarea className={`${inputClass} mt-3 min-h-24`} onChange={(e)=>setNote(e.target.value)} placeholder="Call context, objection, partner approval…" value={note}/><button className="mt-2 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white" onClick={()=>void addNote()} type="button"><Save className="size-4"/>Save note</button></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">Activity timeline</h3><div className="mt-4 space-y-4">{timeline.map((item)=><div className="relative border-l-2 border-slate-200 pl-5" key={item.id}><span className="absolute -left-[5px] top-1 size-2 rounded-full bg-emerald-500"/><p className="text-sm font-bold text-slate-700">{item.body}</p><p className="mt-1 text-xs font-semibold text-slate-400">{formatDate(item.createdAt)} · {item.actor}</p></div>)}{!timeline.length?<p className="text-sm font-semibold text-slate-500">No activity recorded.</p>:null}</div></section></div>
    </div>
  </AdminPlatformShell>
}
function Badge({text,tone}:{text:string;tone:"rose"|"sky"|"amber"|"slate"}){const s={rose:"bg-rose-50 text-rose-700",sky:"bg-sky-50 text-sky-700",amber:"bg-amber-50 text-amber-700",slate:"bg-slate-100 text-slate-700"};return <span className={`rounded-lg px-2.5 py-1 text-xs font-black ${s[tone]}`}>{text}</span>}
function Info({icon:Icon,label,value}:{icon:typeof Target;label:string;value:string}){return <div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-600"><Icon className="size-4"/></span><div><p className="text-xs font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div></div>}
function Score({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-white/10 p-3"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function formatMobile(value:string){const d=normalizeLeadMobile(value);return d.length===10?`+91 ${d.slice(0,5)} ${d.slice(5)}`:value}
function formatDate(value:string){return new Date(value).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true})}
function formatDay(value:string){return new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
