"use client";

import { AdminPlatformShell } from "@/components/admin-platform-shell";
import { createLeadActivity, nextPendingFollowUp, normalizeLead } from "@/lib/lead-utils";
import { rankNextBestActions } from "@/lib/crm-workflow";
import { hydrateLiveState, LIVE_STATE_STORAGE_KEYS, readLocalArray, saveLiveState } from "@/lib/live-state";
import type { Lead, LeadFollowUp } from "@/lib/types";
import { AlertTriangle, ArrowRight, CalendarClock, CheckCircle2, Clock3, Flame, Phone, Target, UserPlus, UsersRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

export default function CrmTodayPage() {
  const [leads, setLeads] = useState<Lead[]>([]);
  const [callLead, setCallLead] = useState<Lead | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { const load=()=>setLeads(readLocalArray<unknown>(LIVE_STATE_STORAGE_KEYS.leads).map(normalizeLead)); load(); void hydrateLiveState().then(load); }, []);
  const ranked = useMemo(() => rankNextBestActions(leads.filter((lead) => !lead.blocked)), [leads]);
  const active = leads.filter((lead) => !lead.blocked && !["Won","Lost"].includes(lead.stage));
  const counts = {
    hot: active.filter((lead) => lead.priority === "Hot" || lead.score >= 65).length,
    due: active.filter((lead) => { const next=nextPendingFollowUp(lead.followUps ?? []); return next && isToday(next.dueAt); }).length,
    overdue: active.filter((lead) => { const next=nextPendingFollowUp(lead.followUps ?? []); return next && new Date(next.dueAt) < new Date(); }).length,
    meetings: active.flatMap((lead) => lead.followUps ?? []).filter((item) => item.type === "Meeting" && !item.completed && isToday(item.dueAt)).length,
    newLeads: leads.filter((lead) => isToday(lead.createdAt)).length,
    noAction: active.filter((lead) => !nextPendingFollowUp(lead.followUps ?? [])).length
  };
  async function save(next: Lead[]) { setLeads(next); await saveLiveState({ leads: next }); }
  async function completeNext(lead: Lead) { const target=nextPendingFollowUp(lead.followUps ?? []); if (!target) return; const followUps=(lead.followUps ?? []).map((item)=>item.id===target.id?{...item,completed:true,completedAt:new Date().toISOString()}:item); await save(leads.map((item)=>item.id===lead.id?normalizeLead({...item,followUps,nextFollowUp:nextPendingFollowUp(followUps)?.dueAt ?? "",activities:[createLeadActivity("follow_up","Next action completed."),...(item.activities ?? [])]}):item)); setMessage(`${lead.name}: action completed.`); }
  const top = ranked[0];
  return <AdminPlatformShell activeLabel="CRM Today" description="Your prioritized sales work—who to contact, why, and what to do next." title="Today">
    {message ? <div className="mb-4 flex items-center justify-between rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700"><span>{message}</span><button onClick={()=>setMessage("")} type="button"><X className="size-4" /></button></div> : null}
    <div className="mb-5"><p className="text-sm font-black text-slate-500">{greeting()}</p><h2 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Today&apos;s work</h2></div>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">
      <Stat icon={Flame} label="Hot leads" value={counts.hot} tone="rose" /><Stat icon={Phone} label="Calls due" value={counts.due} tone="sky" /><Stat icon={AlertTriangle} label="Overdue" value={counts.overdue} tone="rose" /><Stat icon={CalendarClock} label="Meetings" value={counts.meetings} tone="violet" /><Stat icon={UserPlus} label="New leads" value={counts.newLeads} tone="emerald" /><Stat icon={Clock3} label="No next action" value={counts.noAction} tone="amber" />
    </section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-200 p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Next best action</p><h3 className="mt-1 text-xl font-black text-slate-950">Contact this lead now</h3></header>{top ? <div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="rounded-lg bg-rose-50 px-2.5 py-1 text-xs font-black text-rose-700">{top.lead.priority}</span><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-black text-slate-600">Score {top.lead.score}/100</span></div><h4 className="mt-4 text-2xl font-black">{top.lead.name}</h4><p className="mt-1 text-sm font-semibold text-slate-500">{top.lead.interest || "General enquiry"} · {top.lead.city || top.lead.source}</p></div><span className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-black text-amber-800">Priority {top.points}</span></div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-black uppercase text-amber-800">Why now</p><p className="mt-1 text-sm font-bold text-amber-950">{top.reason}</p><p className="mt-2 text-xs font-semibold text-amber-800">Recommended: {top.recommendedAction}{top.dueAt ? ` · ${formatDateTime(top.dueAt)}` : " · schedule the next action"}</p></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3"><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-sky-600 px-3 py-3 text-sm font-black text-white" onClick={()=>setCallLead(top.lead)} type="button"><Phone className="size-4" />Call now</button><a className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-3 text-sm font-black text-slate-700" href={`/crm/leads/${encodeURIComponent(top.lead.id)}`}>Open lead<ArrowRight className="size-4" /></a><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-3 text-sm font-black text-emerald-700" onClick={()=>void completeNext(top.lead)} type="button"><CheckCircle2 className="size-4" />Complete</button></div></div> : <Empty />}</section>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b border-slate-200 p-5"><div><h3 className="text-xl font-black">Priority queue</h3><p className="mt-1 text-sm font-semibold text-slate-500">Deterministic ranking, highest urgency first.</p></div><a className="text-sm font-black text-emerald-700" href="/crm/follow-ups">All tasks</a></header><div className="divide-y divide-slate-100">{ranked.slice(0,7).map((item,index)=><a className="flex items-center gap-3 p-4 hover:bg-slate-50" href={`/crm/leads/${encodeURIComponent(item.lead.id)}`} key={item.lead.id}><span className={`grid size-9 shrink-0 place-items-center rounded-lg text-xs font-black ${index < 3 ? "bg-slate-950 text-white" : "bg-slate-100 text-slate-600"}`}>{index+1}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-black">{item.lead.name}</span><span className="mt-1 block truncate text-xs font-semibold text-slate-500">{item.reason}</span></span><span className="text-xs font-black text-slate-400">{item.recommendedAction}</span></a>)}</div></section>
    </div>
    {callLead ? <CallOutcomeModal lead={callLead} onClose={()=>setCallLead(null)} onSave={async (outcome,note,nextType,nextAt)=>{ const now=new Date().toISOString(); const followUp:LeadFollowUp|undefined=nextAt?{id:`followup-${Date.now().toString(36)}`,dueAt:new Date(nextAt).toISOString(),type:nextType,note,completed:false,createdAt:now}:undefined; const next=leads.map((lead)=>lead.id===callLead.id?normalizeLead({...lead,stage:outcome==="Interested"&&lead.stage==="New Leads"?"Contacted":lead.stage,callHistory:[`${outcome}: ${note}`,...lead.callHistory],followUps:followUp?[followUp,...(lead.followUps??[])]:lead.followUps,nextFollowUp:followUp?.dueAt??lead.nextFollowUp,lastActivityAt:now,activities:[createLeadActivity("call",`Call outcome: ${outcome}${note?` · ${note}`:""}`),...(followUp?[createLeadActivity("follow_up",`${nextType} scheduled for ${formatDateTime(followUp.dueAt)}.`)]:[]),...(lead.activities??[])]}):lead); await save(next); setCallLead(null); setMessage(`${callLead.name}: call outcome saved.`);}} />:null}
  </AdminPlatformShell>;
}

function CallOutcomeModal({lead,onClose,onSave}:{lead:Lead;onClose:()=>void;onSave:(outcome:string,note:string,type:LeadFollowUp["type"],at:string)=>void}) { const [outcome,setOutcome]=useState("Connected"); const [note,setNote]=useState(""); const [type,setType]=useState<LeadFollowUp["type"]>("Call"); const [at,setAt]=useState(""); return <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/50 sm:place-items-center sm:p-4"><form className="w-full bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-2xl" onSubmit={(e)=>{e.preventDefault();onSave(outcome,note,type,at)}}><div className="flex justify-between"><div><h3 className="text-xl font-black">Call outcome</h3><p className="mt-1 text-sm font-semibold text-slate-500">{lead.name} · {lead.mobile}</p></div><button onClick={onClose} type="button"><X className="size-5" /></button></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{["Connected","Not Reachable","Busy","Switched Off","Wrong Number","Interested","Not Interested","Call Back Later","No Response"].map((value)=><button className={`rounded-lg border px-2 py-2.5 text-xs font-black ${outcome===value?"border-slate-950 bg-slate-950 text-white":"border-slate-200 text-slate-600"}`} key={value} onClick={()=>setOutcome(value)} type="button">{value}</button>)}</div><textarea className="mt-4 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm font-semibold" onChange={(e)=>setNote(e.target.value)} placeholder="Call notes / objection" value={note}/><p className="mt-4 text-xs font-black uppercase text-slate-500">What&apos;s next?</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><select className="rounded-xl border border-slate-200 p-3 text-sm font-bold" onChange={(e)=>setType(e.target.value as LeadFollowUp["type"])} value={type}>{["Call","Meeting","Send Information","Partner Call","Payment Follow-up"].map((v)=><option key={v}>{v}</option>)}</select><input className="rounded-xl border border-slate-200 p-3 text-sm font-bold" onChange={(e)=>setAt(e.target.value)} type="datetime-local" value={at}/></div><button className="mt-4 w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white" type="submit">Save outcome</button></form></div> }
function Stat({icon:Icon,label,value,tone}:{icon:typeof Flame;label:string;value:number;tone:"rose"|"sky"|"violet"|"emerald"|"amber"}){const styles={rose:"bg-rose-50 text-rose-700",sky:"bg-sky-50 text-sky-700",violet:"bg-violet-50 text-violet-700",emerald:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700"};return <div className="rounded-xl border border-slate-200 bg-white p-4"><span className={`grid size-9 place-items-center rounded-lg ${styles[tone]}`}><Icon className="size-4"/></span><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-black uppercase text-slate-500">{label}</p></div>}
function Empty(){return <div className="grid min-h-72 place-items-center p-6 text-center"><div><Target className="mx-auto size-8 text-slate-300"/><p className="mt-3 font-black">No active leads</p><p className="mt-1 text-sm font-semibold text-slate-500">New assigned leads will appear here.</p></div></div>}
function greeting(){const hour=new Date().getHours();return hour<12?"GOOD MORNING":hour<17?"GOOD AFTERNOON":"GOOD EVENING"}
function isToday(value:string){const date=new Date(value);const now=new Date();return !Number.isNaN(date.getTime())&&date.toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"})===now.toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"})}
function formatDateTime(value:string){return new Date(value).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:true})}
