"use client";

import { AdminPlatformShell } from "@/components/admin-platform-shell";
import { detectLeadRisk } from "@/lib/crm-workflow";
import { normalizeLead } from "@/lib/lead-utils";
import { hydrateLiveState, LIVE_STATE_STORAGE_KEYS, readLocalArray } from "@/lib/live-state";
import type { Lead } from "@/lib/types";
import { AlertTriangle, BarChart3, CircleDollarSign, Target, TrendingUp, UserRound, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

export default function CrmAnalyticsPage(){
  const [leads,setLeads]=useState<Lead[]>([]);useEffect(()=>{const load=()=>setLeads(readLocalArray<unknown>(LIVE_STATE_STORAGE_KEYS.leads).map(normalizeLead));load();void hydrateLiveState().then(load)},[]);
  const active=leads.filter((l)=>!["Won","Lost"].includes(l.stage));const won=leads.filter((l)=>l.stage==="Won");const lost=leads.filter((l)=>l.stage==="Lost");
  const sourceRows=useMemo(()=>group(leads,(l)=>l.source||"Unknown"),[leads]);const ownerRows=useMemo(()=>group(leads,(l)=>l.assignedTo||"Unassigned"),[leads]);const risks=active.map((lead)=>({lead,risk:detectLeadRisk(lead)})).filter((x)=>x.risk);
  const funnel=["New Leads","Contacted","Qualified","Proposal","Won"].map((stage)=>({stage,count:leads.filter((l)=>l.stage===stage).length}));const max=Math.max(1,...funnel.map((x)=>x.count));
  return <AdminPlatformShell activeLabel="CRM Analytics" description="Actionable funnel, source, workload and revenue-risk visibility." title="CRM Analytics">
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4"><Kpi icon={UsersRound} label="Total leads" value={leads.length}/><Kpi icon={Target} label="Active" value={active.length}/><Kpi icon={TrendingUp} label="Won" value={won.length}/><Kpi icon={CircleDollarSign} label="Open value" value={`INR ${active.reduce((s,l)=>s+l.revenuePotential,0).toLocaleString("en-IN")}`}/></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-xl font-black">Conversion funnel</h3><p className="mt-1 text-sm font-semibold text-slate-500">Current lead distribution by sales stage.</p><div className="mt-5 space-y-4">{funnel.map((row)=><div key={row.stage}><div className="flex justify-between text-sm font-black"><span>{row.stage}</span><span>{row.count}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{width:`${Math.max(row.count?6:0,row.count/max*100)}%`}}/></div></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-rose-50 text-rose-700"><AlertTriangle className="size-5"/></span><div><h3 className="text-xl font-black">Sales at risk</h3><p className="text-sm font-semibold text-slate-500">Deterministic SLA and stuck-lead rules.</p></div></div><div className="mt-4 divide-y divide-slate-100 rounded-xl border border-slate-200">{risks.slice(0,10).map(({lead,risk})=><a className="flex items-center justify-between gap-3 p-3 hover:bg-slate-50" href={`/crm/leads/${encodeURIComponent(lead.id)}`} key={lead.id}><div><p className="text-sm font-black">{lead.name}</p><p className="mt-1 text-xs font-semibold text-slate-500">{lead.assignedTo||"Unassigned"} · {lead.stage}</p></div><span className="rounded-lg bg-rose-50 px-2 py-1 text-[10px] font-black text-rose-700">{risk?.replaceAll("_"," ")}</span></a>)}{!risks.length?<p className="p-6 text-center text-sm font-bold text-slate-500">No active risks detected.</p>:null}</div></section></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Breakdown title="Leads by source" rows={sourceRows}/><Breakdown title="Counselor workload" rows={ownerRows}/></div>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><h3 className="text-xl font-black">Lost reason distribution</h3><div className="mt-4 flex flex-wrap gap-2">{group(lost,(l)=>l.lostReason||"Reason missing").map((row)=><span className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-black" key={row.label}>{row.label} <strong className="ml-2 text-rose-600">{row.count}</strong></span>)}{!lost.length?<p className="text-sm font-semibold text-slate-500">No lost leads recorded.</p>:null}</div></section>
  </AdminPlatformShell>
}
function group(leads:Lead[],key:(lead:Lead)=>string){const map=new Map<string,number>();leads.forEach((l)=>{const k=key(l);map.set(k,(map.get(k)??0)+1)});return [...map].map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count)}
function Kpi({icon:Icon,label,value}:{icon:typeof UsersRound;label:string;value:number|string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><span className="grid size-9 place-items-center rounded-lg bg-slate-100 text-slate-600"><Icon className="size-4"/></span><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-black uppercase text-slate-500">{label}</p></div>}
function Breakdown({title,rows}:{title:string;rows:{label:string;count:number}[]}){const max=Math.max(1,...rows.map((r)=>r.count));return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><BarChart3 className="size-5 text-emerald-600"/><h3 className="text-xl font-black">{title}</h3></div><div className="mt-4 space-y-3">{rows.slice(0,10).map((row)=><div className="grid grid-cols-[minmax(100px,1fr)_2fr_36px] items-center gap-3" key={row.label}><span className="truncate text-sm font-bold">{row.label}</span><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{width:`${row.count/max*100}%`}}/></div><span className="text-right text-sm font-black">{row.count}</span></div>)}</div></section>}
