import type { Connection, NodeKind, WorkflowNode } from "./workflow-studio.ts";

export type WorkflowTemplate = { id: string; name: string; description: string; category: string; accent: string; nodes: WorkflowNode[]; connections: Connection[] };

const allowedKinds = new Set<NodeKind>(["trigger", "condition", "crm", "workshop", "attendance", "message", "payment", "delay", "webhook", "ai", "data", "telegram"]);
const node = (id: string, kind: NodeKind, title: string, x: number, config: Record<string, unknown>, subtitle = "Ready to configure"): WorkflowNode => ({ id, kind, title, subtitle, x, y: 280, config });
const connect = (ids: string[]) => ids.slice(1).map((id, index) => ({ id: `c-${ids[index]}-${id}`, from: ids[index], to: id }));

export const workflowTemplates: WorkflowTemplate[] = [
  { id: "attendance-cross-workshop-confirmation", name: "Attendance → workshop confirmation", description: "When a participant attends the selected workshop sessions, find their waiting registration in another workshop and confirm it safely.", category: "Attendance", accent: "teal", nodes: [node("attendance", "attendance", "Attendance submitted", 80, { event: "Attendance submitted", source: "Selected attendance form", deduplicate: true }), node("threshold", "attendance", "Check session attendance count", 340, { match: "Mobile number", status: "Present", minimumSessions: 1 }), node("waiting", "workshop", "Find waiting registration", 600, { workshop: "Healthy Forever", match: "Mobile number", registrationMode: "Existing or new", status: "Waiting only" }), node("confirm", "workshop", "Confirm waiting registration", 860, { workshop: "Healthy Forever", capacity: "Respect capacity", action: "Confirm registration", confirmationSource: "Attendance" }), node("notify", "message", "Send confirmation notice", 1120, { template: "cfl_registration_confirmation_v3", recipient: "{{registration.mobile}}", retry: true })], connections: connect(["attendance", "threshold", "waiting", "confirm", "notify"]) },
  { id: "telegram-ai-data-assistant", name: "Telegram AI data assistant", description: "Let approved Telegram chats ask dashboard questions; fetch only allowed read-only data and return a grounded AI answer.", category: "AI", accent: "indigo", nodes: [node("telegram", "telegram", "Telegram message received", 80, { event: "Telegram message received", chatPolicy: "Approved chats only", deduplicate: true }), node("guard", "condition", "Authorize Telegram chat", 340, { field: "Telegram chat ID", operator: "Is approved", value: "" }), node("query", "data", "Query dashboard data", 600, { scope: "Dashboard summary", access: "Read only", maxRows: 25, redactSensitive: true }), node("agent", "ai", "AI data agent", 860, { provider: "Local Ollama", model: "From server settings", instruction: "Answer only from the connected dashboard data. Say when data is unavailable.", language: "Auto detect", citations: true }), node("reply", "telegram", "Send Telegram reply", 1120, { credential: "Telegram bot · Primary", message: "{{ai.answer}}", parseMode: "Plain text", splitLongMessages: true })], connections: connect(["telegram", "guard", "query", "agent", "reply"]) },
  { id: "smart-registration", name: "Smart registration routing", description: "Validate a registration, assign the best salesperson, reserve a batch and send confirmation.", category: "Registration", accent: "emerald", nodes: [node("trigger", "trigger", "Registration received", 80, { event: "New public registration", deduplicate: true }), node("validate", "condition", "Validate mobile", 340, { field: "Registration mobile", operator: "Is valid" }), node("assign", "crm", "Assign sales person", 600, { fallbackStrategy: "least-active", assignmentRules: [] }), node("batch", "workshop", "Assign workshop & batch", 860, { batch: "Best available batch", capacity: "Respect capacity" }), node("confirm", "message", "Send WhatsApp confirmation", 1120, { template: "cfl_registration_confirmation_v3", retry: true })], connections: connect(["trigger", "validate", "assign", "batch", "confirm"]) },
  { id: "attendance-recovery", name: "Attendance & no-show recovery", description: "React to attendance, promote eligible participants and create no-show recovery tasks.", category: "Attendance", accent: "teal", nodes: [node("attendance", "attendance", "Attendance submitted", 120, { event: "Attendance submitted", deduplicate: true }), node("status", "attendance", "Check attendee status", 400, { match: "Mobile number" }), node("promote", "workshop", "Promote waiting registration", 680, { capacity: "Respect capacity" }), node("followup", "crm", "Create no-show follow-up", 960, { action: "Create follow-up", taskType: "Call", due: "Today" })], connections: connect(["attendance", "status", "promote", "followup"]) },
  { id: "payment-recovery", name: "Payment recovery", description: "Reconcile captured payments and route failed payments into a sales recovery sequence.", category: "Payments", accent: "rose", nodes: [node("payment", "payment", "Payment failed", 160, { event: "Payment failed", provider: "Razorpay" }), node("delay", "delay", "Wait 15 minutes", 450, { amount: 15, unit: "Minutes" }), node("message", "message", "Send payment reminder", 740, { template: "cfl_payment_reminder", retry: true }), node("task", "crm", "Create payment follow-up", 1030, { taskType: "Payment Follow-up", priority: "High", due: "Today" })], connections: connect(["payment", "delay", "message", "task"]) },
  { id: "whatsapp-handoff", name: "WhatsApp sales handoff", description: "Detect a reply, classify intent and hand the conversation to the assigned salesperson.", category: "Messaging", accent: "sky", nodes: [node("reply", "trigger", "WhatsApp reply received", 160, { event: "WhatsApp reply received", deduplicate: true }), node("intent", "condition", "Check reply intent", 460, { field: "Message text", operator: "Contains", value: "call" }), node("handoff", "crm", "Hand off to sales inbox", 760, { action: "Create conversation task", priority: "High", due: "Immediately" }), node("ack", "message", "Send handoff acknowledgement", 1060, { messageType: "buttons", template: "cfl_sales_handoff" })], connections: connect(["reply", "intent", "handoff", "ack"]) },
  { id: "sla-rescue", name: "Lead SLA rescue", description: "Escalate missed first-response SLAs and automatically create urgent recovery actions.", category: "CRM", accent: "violet", nodes: [node("sla", "trigger", "Lead SLA breached", 180, { event: "Lead SLA breached", deduplicate: true }), node("priority", "condition", "Check lead priority", 480, { field: "Lead priority", operator: "Equals", value: "Hot" }), node("escalate", "crm", "Escalate to sales manager", 780, { action: "Escalate lead", priority: "Urgent", notifyManager: true }), node("followup", "crm", "Create CRM follow-up", 1080, { action: "Create follow-up", taskType: "Call", due: "Immediately" })], connections: connect(["sla", "priority", "escalate", "followup"]) },
  { id: "new-lead-welcome", name: "New lead welcome sequence", description: "Respond quickly to every new lead, assign an owner and create the first-call task.", category: "CRM", accent: "violet", nodes: [node("lead", "trigger", "Registration received", 120, { event: "New public registration", deduplicate: true }), node("tag", "crm", "Add new lead tag", 390, { tag: "New lead" }), node("owner", "crm", "Assign sales person", 660, { fallbackStrategy: "round-robin" }), node("welcome", "message", "Send welcome WhatsApp", 930, { template: "cfl_lead_welcome_v1", retry: true }), node("call", "crm", "Create first-call follow-up", 1200, { taskType: "Call", due: "Within 15 minutes", priority: "High" })], connections: connect(["lead", "tag", "owner", "welcome", "call"]) },
  { id: "appointment-reminder", name: "Consultation reminder", description: "Send a timed reminder before a sales consultation and flag missed appointments for follow-up.", category: "Messaging", accent: "sky", nodes: [node("scheduled", "delay", "Schedule for date", 120, { scheduleEnabled: true, frequency: "once" }), node("reminder", "message", "Send consultation reminder", 400, { template: "cfl_consultation_reminder_v1", retry: true }), node("wait", "delay", "Wait 2 hours", 680, { amount: 2, unit: "Hours" }), node("check", "condition", "Check appointment status", 960, { field: "Appointment status", operator: "Equals", value: "Missed" }), node("task", "crm", "Create missed-call follow-up", 1240, { taskType: "Call", due: "Today", priority: "High" })], connections: connect(["scheduled", "reminder", "wait", "check", "task"]) },
  { id: "installment-due", name: "Installment due reminder", description: "Nudge part-payment customers before the due date and create a recovery task if payment is pending.", category: "Payments", accent: "rose", nodes: [node("due", "delay", "Schedule for date", 120, { scheduleEnabled: true, frequency: "once" }), node("status", "payment", "Check payment status", 390, { provider: "Razorpay" }), node("pending", "condition", "Payment still pending", 660, { field: "Payment status", operator: "Equals", value: "Pending" }), node("message", "message", "Send installment reminder", 930, { template: "cfl_installment_due_v1", retry: true }), node("followup", "crm", "Create payment follow-up", 1200, { taskType: "Payment Follow-up", due: "Today", priority: "High" })], connections: connect(["due", "status", "pending", "message", "followup"]) },
  { id: "payment-receipt", name: "Payment receipt & thank you", description: "Send a receipt after a successful payment and mark the customer ready for onboarding.", category: "Payments", accent: "rose", nodes: [node("paid", "trigger", "Payment completed", 140, { event: "Payment completed", deduplicate: true }), node("update", "payment", "Update payment status", 430, { status: "Paid" }), node("receipt", "message", "Send payment receipt", 720, { template: "cfl_payment_receipt_v1", retry: true }), node("tag", "crm", "Add paid customer tag", 1010, { tag: "Paid customer" }), node("onboard", "crm", "Create onboarding follow-up", 1300, { taskType: "Onboarding", due: "Today" })], connections: connect(["paid", "update", "receipt", "tag", "onboard"]) },
  { id: "waitlist-capacity", name: "Waitlist capacity release", description: "Promote the next eligible person when a batch seat opens and notify the sales team.", category: "Workshop", accent: "teal", nodes: [node("seat", "trigger", "Batch seat available", 130, { event: "Capacity available", deduplicate: true }), node("waitlist", "workshop", "Check waiting list", 410, { capacity: "Respect capacity" }), node("promote", "workshop", "Assign batch", 690, { batch: "Next available" }), node("notice", "message", "Send seat available message", 970, { template: "cfl_waitlist_promotion_v1" }), node("confirm", "crm", "Create confirmation follow-up", 1250, { taskType: "Call", due: "Today" })], connections: connect(["seat", "waitlist", "promote", "notice", "confirm"]) },
  { id: "workshop-reminder", name: "Workshop day reminder", description: "Send a practical event reminder, venue details and an attendance check before each workshop.", category: "Workshop", accent: "teal", nodes: [node("schedule", "delay", "Schedule for date", 120, { scheduleEnabled: true, frequency: "once" }), node("details", "workshop", "Check workshop details", 400, { action: "Load workshop" }), node("reminder", "message", "Send workshop reminder", 680, { template: "cfl_workshop_reminder_v4", retry: true }), node("attendance", "attendance", "Prepare attendance list", 960, { action: "Prepare roster" })], connections: connect(["schedule", "details", "reminder", "attendance"]) },
  { id: "feedback-collection", name: "Post-workshop feedback", description: "Ask attendees for feedback after a session and route unhappy responses to the service team.", category: "Attendance", accent: "teal", nodes: [node("complete", "trigger", "Workshop completed", 120, { event: "Workshop completed" }), node("wait", "delay", "Wait 2 hours", 390, { amount: 2, unit: "Hours" }), node("ask", "message", "Send feedback request", 660, { messageType: "buttons", template: "cfl_feedback_request_v1" }), node("score", "condition", "Check feedback score", 930, { field: "Feedback score", operator: "Is before", value: "4" }), node("service", "crm", "Create service recovery task", 1200, { taskType: "Service recovery", priority: "High", due: "Today" })], connections: connect(["complete", "wait", "ask", "score", "service"]) },
  { id: "referral-thank-you", name: "Referral thank-you", description: "Thank a customer for a referral, tag the source and create a follow-up for the referred lead.", category: "CRM", accent: "violet", nodes: [node("referral", "trigger", "Referral received", 130, { event: "Referral received", deduplicate: true }), node("tag", "crm", "Add referral source tag", 410, { tag: "Referral" }), node("thank", "message", "Send referral thank-you", 690, { template: "cfl_referral_thank_you_v1" }), node("assign", "crm", "Assign sales person", 970, { fallbackStrategy: "least-active" }), node("followup", "crm", "Create referral follow-up", 1250, { taskType: "Call", due: "Today", priority: "High" })], connections: connect(["referral", "tag", "thank", "assign", "followup"]) },
  { id: "inactive-lead-reengagement", name: "Inactive lead re-engagement", description: "Re-engage leads with no recent activity and hand warm replies back to a salesperson.", category: "CRM", accent: "violet", nodes: [node("inactive", "trigger", "Follow-up overdue", 120, { event: "Follow-up overdue", deduplicate: true }), node("wait", "delay", "Wait 1 day", 390, { amount: 1, unit: "Days" }), node("message", "message", "Send re-engagement message", 660, { template: "cfl_reengagement_v1" }), node("reply", "condition", "Check for reply", 930, { field: "WhatsApp reply", operator: "Equals", value: "Received" }), node("handoff", "crm", "Hand off to sales inbox", 1200, { taskType: "Call", priority: "High", due: "Immediately" })], connections: connect(["inactive", "wait", "message", "reply", "handoff"]) },
  { id: "city-based-routing", name: "City-based lead routing", description: "Route enquiries by city, then allocate them to the right local salesperson and batch.", category: "Registration", accent: "emerald", nodes: [node("registration", "trigger", "Registration received", 120, { event: "New public registration", deduplicate: true }), node("city", "condition", "Route by city / date", 400, { field: "Registration city", operator: "Equals" }), node("assign", "crm", "Assign sales person", 680, { assignmentRules: [], fallbackStrategy: "least-active" }), node("batch", "workshop", "Assign workshop & batch", 960, { batch: "City matching batch" }), node("message", "message", "Send local workshop confirmation", 1240, { template: "cfl_city_workshop_confirmation_v1" })], connections: connect(["registration", "city", "assign", "batch", "message"]) },
  { id: "post-workshop-upsell", name: "Post-workshop upsell", description: "Offer the next programme to engaged attendees and create a sales task for interested replies.", category: "Sales", accent: "sky", nodes: [node("attended", "trigger", "Attendance submitted", 120, { event: "Attendance submitted", deduplicate: true }), node("engaged", "condition", "Check attendee status", 400, { field: "Attendance status", operator: "Equals", value: "Present" }), node("wait", "delay", "Wait 1 day", 680, { amount: 1, unit: "Days" }), node("offer", "message", "Send next programme offer", 960, { template: "cfl_next_programme_offer_v1" }), node("task", "crm", "Create upsell follow-up", 1240, { taskType: "Sales call", priority: "Medium", due: "Tomorrow" })], connections: connect(["attended", "engaged", "wait", "offer", "task"]) },
  { id: "coupon-abandonment", name: "Coupon recovery", description: "Recover a stalled checkout by reminding eligible leads about their applied coupon.", category: "Payments", accent: "rose", nodes: [node("coupon", "trigger", "Coupon applied", 120, { event: "Coupon applied", deduplicate: true }), node("wait", "delay", "Wait 30 minutes", 390, { amount: 30, unit: "Minutes" }), node("status", "payment", "Check payment status", 660, { provider: "Razorpay" }), node("pending", "condition", "Payment not completed", 930, { field: "Payment status", operator: "Equals", value: "Pending" }), node("reminder", "message", "Send coupon checkout reminder", 1200, { template: "cfl_coupon_reminder_v1" })], connections: connect(["coupon", "wait", "status", "pending", "reminder"]) },
  { id: "manual-registration-review", name: "Manual registration review", description: "Verify manually entered registrations before assigning a batch and sending confirmation.", category: "Registration", accent: "emerald", nodes: [node("manual", "trigger", "Manual registration created", 120, { event: "Manual registration" }), node("validate", "condition", "Validate mobile", 400, { field: "Registration mobile", operator: "Is valid" }), node("review", "crm", "Create registration review task", 680, { taskType: "Review", due: "Today" }), node("batch", "workshop", "Assign workshop & batch", 960, { batch: "Best available batch" }), node("confirm", "message", "Send registration confirmation", 1240, { template: "cfl_registration_confirmation_v3" })], connections: connect(["manual", "validate", "review", "batch", "confirm"]) },
  { id: "membership-renewal", name: "Membership renewal reminder", description: "Notify members before expiry and create a renewal task if their payment remains outstanding.", category: "Payments", accent: "rose", nodes: [node("renewal", "delay", "Schedule for date", 120, { scheduleEnabled: true, frequency: "once" }), node("message", "message", "Send renewal reminder", 400, { template: "cfl_membership_renewal_v1", retry: true }), node("wait", "delay", "Wait 3 days", 680, { amount: 3, unit: "Days" }), node("payment", "payment", "Check payment status", 960, { provider: "Razorpay" }), node("task", "crm", "Create renewal follow-up", 1240, { taskType: "Renewal", priority: "High", due: "Today" })], connections: connect(["renewal", "message", "wait", "payment", "task"]) },
  { id: "daily-sales-digest", name: "Daily sales follow-up digest", description: "Create a scheduled priority queue for overdue and high-intent leads each morning.", category: "CRM", accent: "violet", nodes: [node("schedule", "delay", "Scheduled time", 120, { scheduleEnabled: true, frequency: "daily", time: "09:00", timezone: "Asia/Kolkata" }), node("overdue", "crm", "Find overdue follow-ups", 410, { action: "Find overdue" }), node("priority", "condition", "Filter high-intent leads", 700, { field: "Lead priority", operator: "Equals", value: "Hot" }), node("assign", "crm", "Reassign inactive lead", 990, { action: "Reassign inactive" }), node("alert", "message", "Send team priority digest", 1280, { template: "cfl_daily_sales_digest_v1" })], connections: connect(["schedule", "overdue", "priority", "assign", "alert"]) }
];

export function parseWorkflowImport(text: string) {
  if (new TextEncoder().encode(text).length > 1_048_576) throw new Error("Workflow file exceeds the 1 MB import limit.");
  let raw: unknown;
  try { raw = JSON.parse(text); } catch { throw new Error("Choose a valid workflow JSON file."); }
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error("Workflow JSON must be an object.");
  const value = raw as Record<string, unknown>;
  if (!Array.isArray(value.nodes) || !Array.isArray(value.connections) || !value.nodes.length || value.nodes.length > 100 || value.connections.length > 250) throw new Error("Workflow must contain 1–100 nodes and no more than 250 connections.");
  const ids = new Set<string>();
  const nodes = value.nodes.map((item) => {
    if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error("Every workflow node must be an object.");
    const candidate = item as Record<string, unknown>; const id = String(candidate.id || "").slice(0, 160); const kind = String(candidate.kind || "") as NodeKind;
    if (!id || ids.has(id) || !allowedKinds.has(kind)) throw new Error("Workflow contains an invalid or duplicate node.");
    ids.add(id);
    return { id, kind, title: String(candidate.title || "Untitled node").slice(0, 160), subtitle: String(candidate.subtitle || "Imported node").slice(0, 200), x: Math.max(0, Math.min(4000, Number(candidate.x) || 0)), y: Math.max(0, Math.min(2400, Number(candidate.y) || 0)), config: candidate.config && typeof candidate.config === "object" && !Array.isArray(candidate.config) ? candidate.config as Record<string, unknown> : {} } satisfies WorkflowNode;
  });
  const connectionIds = new Set<string>();
  const connections = value.connections.map((item) => {
    if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error("Every connection must be an object.");
    const candidate = item as Record<string, unknown>; const id = String(candidate.id || "").slice(0, 160); const from = String(candidate.from || ""); const to = String(candidate.to || "");
    if (!id || connectionIds.has(id) || !ids.has(from) || !ids.has(to) || from === to) throw new Error("Workflow contains an invalid connection.");
    connectionIds.add(id);
    return { id, from, to, label: candidate.label ? String(candidate.label).slice(0, 80) : undefined, dashed: candidate.dashed === true } satisfies Connection;
  });
  return { name: String(value.name || "Imported workflow").slice(0, 160), active: false, note: String(value.note || "").slice(0, 10_000), nodes, connections };
}
