"use client";

import { AdminPlatformShell } from "@/components/admin-platform-shell";
import { calculateSessionScorecard, SCORECARD_CONFIG, type InstantSignal, type ScorecardInput } from "@/lib/crm-scorecard";
import { hydrateLiveState, LIVE_STATE_STORAGE_KEYS, readLocalArray } from "@/lib/live-state";
import type { Lead } from "@/lib/types";
import { ArrowLeft, ArrowRight, CalendarPlus, Check, ChevronRight, Clock3, MapPin, Medal, Plus, RefreshCw, Save, Search, Target, UserPlus, UsersRound, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

type Session = { id: string; name: string; session_date: string; start_time?: string; location: string; status: string; registrations: number };
type Participant = Record<string, unknown> & { id: string; lead_name: string; business: string; mobile: string; observer: string; sequence: number; rank: number | null; meetingPriority: string; calculated_tier?: string; total_score?: number; pre_score?: number; session_score?: number; attended?: boolean; meeting_id?: string; meeting_at?: string };
type Detail = { session: Session; participants: Participant[]; summary: { registrations: number; attended: number; notAttended: number; tierA: number; tierB: number; tierC: number; meetingsBooked: number; showUpRate: number; meetingBookingRate: number; expectedEnrollments: number } };

const initialAnswers: ScorecardInput = { turnoverOption: "UNKNOWN", teamSizeOption: "SOLO", timeFreedomOption: "UNKNOWN", vintageOption: "BELOW_1", attended: false, onTime: false, notesTaken: false, askedQuestion: false, stayedUntilEnd: false, cameWithSomeone: false, metPersonally: false, instantSignal: "-" };
const inputClass = "w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-bold outline-none";

export default function CrmSessionsPage() {
  const [sessions, setSessions] = useState<Session[]>([]);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [leads, setLeads] = useState<Lead[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [participantOpen, setParticipantOpen] = useState(false);
  const [scoreTarget, setScoreTarget] = useState<Participant | null>(null);

  const loadSessions = useCallback(async () => {
    setError("");
    try { const response = await fetch("/api/crm/sales-sessions", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSessions(data.sessions || []); }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to load sessions."); }
  }, []);
  const loadDetail = useCallback(async (id: string) => {
    setBusy(true); setError("");
    try { const response = await fetch(`/api/crm/sales-sessions?sessionId=${encodeURIComponent(id)}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDetail(data); }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to load session."); } finally { setBusy(false); }
  }, []);

  useEffect(() => { void loadSessions(); void hydrateLiveState().then(() => setLeads(readLocalArray<Lead>(LIVE_STATE_STORAGE_KEYS.leads))); }, [loadSessions]);

  async function mutate(body: Record<string, unknown>) {
    setBusy(true); setError("");
    try { const response = await fetch("/api/crm/sales-sessions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
    catch (e) { setError(e instanceof Error ? e.message : "Action failed."); return null; } finally { setBusy(false); }
  }

  return <AdminPlatformShell activeLabel="CRM Sessions" description="Score participants fast, rank attended leads, and turn the strongest intent into meetings." title="Sessions">
    {error ? <div className="mb-4 flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-800"><span>{error}</span><button onClick={() => detail ? void loadDetail(detail.session.id) : void loadSessions()} type="button"><RefreshCw className="size-4" /></button></div> : null}
    {!detail ? <>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Sales sessions</h2><p className="mt-1 text-sm font-semibold text-slate-500">Qualification, observation, ranking and meeting priority in one workflow.</p></div><button className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white" onClick={() => setCreateOpen(true)} type="button"><CalendarPlus className="size-4" />New session</button></div>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        {sessions.length ? <div className="divide-y divide-slate-100">{sessions.map((session) => <button className="flex w-full items-center gap-4 p-4 text-left hover:bg-slate-50 sm:p-5" key={session.id} onClick={() => void loadDetail(session.id)} type="button"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Target className="size-5" /></span><span className="min-w-0 flex-1"><span className="block truncate text-base font-black text-slate-950">{session.name}</span><span className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs font-bold text-slate-500"><span>{formatDate(session.session_date)}</span><span>{session.location || "Location not set"}</span><span>{session.registrations} participants</span></span></span><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-black text-slate-600">{session.status}</span><ChevronRight className="size-5 text-slate-400" /></button>)}</div> : <Empty title="No sales sessions yet" body="Create a session, then add leads and complete their scorecards." />}
      </section>
    </> : <SessionDetail detail={detail} busy={busy} onBack={() => { setDetail(null); void loadSessions(); }} onAdd={() => setParticipantOpen(true)} onRefresh={() => void loadDetail(detail.session.id)} onScore={setScoreTarget} mutate={mutate} />}
    {createOpen ? <CreateSession busy={busy} onClose={() => setCreateOpen(false)} onSave={async (body) => { const data = await mutate({ action: "create_session", ...body }); if (data?.session) { setCreateOpen(false); await loadSessions(); await loadDetail(data.session.id); } }} /> : null}
    {participantOpen && detail ? <AddParticipant leads={leads} busy={busy} onClose={() => setParticipantOpen(false)} onSave={async (lead) => { const data = await mutate({ action: "add_participant", sessionId: detail.session.id, leadId: lead.id, leadName: lead.name, mobile: lead.mobile, business: lead.interest || "", observer: lead.assignedTo || "" }); if (data) { setParticipantOpen(false); await loadDetail(detail.session.id); } }} /> : null}
    {scoreTarget && detail ? <ScorecardSheet participant={scoreTarget} busy={busy} onClose={() => setScoreTarget(null)} onSaved={async () => { setScoreTarget(null); await loadDetail(detail.session.id); }} mutate={mutate} /> : null}
  </AdminPlatformShell>;
}

function SessionDetail({ detail, busy, onBack, onAdd, onRefresh, onScore, mutate }: { detail: Detail; busy: boolean; onBack: () => void; onAdd: () => void; onRefresh: () => void; onScore: (p: Participant) => void; mutate: (body: Record<string, unknown>) => Promise<Record<string, unknown> | null> }) {
  const [view, setView] = useState<"all" | "top9">("all");
  const ranked = [...detail.participants].filter((p) => p.rank).sort((a, b) => Number(a.rank) - Number(b.rank));
  const rows = view === "top9" ? ranked.filter((p) => p.meetingPriority === "TOP_9") : detail.participants;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><button className="mb-3 inline-flex items-center gap-2 text-sm font-black text-slate-500 hover:text-slate-900" onClick={onBack} type="button"><ArrowLeft className="size-4" />All sessions</button><h2 className="text-2xl font-black">{detail.session.name}</h2><p className="mt-1 flex flex-wrap gap-3 text-sm font-semibold text-slate-500"><span>{formatDate(detail.session.session_date)}</span><span className="inline-flex items-center gap-1"><MapPin className="size-3.5" />{detail.session.location || "Not set"}</span></p></div><div className="flex gap-2"><button className="grid size-11 place-items-center rounded-xl border border-slate-200 bg-white" disabled={busy} onClick={onRefresh} type="button"><RefreshCw className={`size-4 ${busy ? "animate-spin" : ""}`} /></button><button className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white" onClick={onAdd} type="button"><UserPlus className="size-4" />Add participant</button></div></div>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">{[["Registered",detail.summary.registrations],["Attended",detail.summary.attended],["Show-up",`${detail.summary.showUpRate}%`],["Tier A",detail.summary.tierA],["Tier B",detail.summary.tierB],["Tier C",detail.summary.tierC],["Meetings",detail.summary.meetingsBooked],["Expected",detail.summary.expectedEnrollments]].map(([label,value]) => <div className="rounded-xl border border-slate-200 bg-white p-3" key={label}><p className="text-[11px] font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p></div>)}</section>
    <div className="flex gap-2"><button className={`rounded-lg px-4 py-2 text-sm font-black ${view === "all" ? "bg-slate-950 text-white" : "bg-white text-slate-600"}`} onClick={() => setView("all")} type="button">All participants</button><button className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-black ${view === "top9" ? "bg-amber-500 text-slate-950" : "bg-white text-slate-600"}`} onClick={() => setView("top9")} type="button"><Medal className="size-4" />Top 9 priority</button></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full"><thead><tr>{["Rank","Lead","Observer","Pre","Session","Total","Instant","Tier","Meeting","Action"].map((h) => <th className="border-b border-slate-200 px-3 py-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((p) => <ParticipantRow key={p.id} participant={p} onScore={() => onScore(p)} mutate={mutate} refresh={onRefresh} />)}</tbody></table></div><div className="divide-y divide-slate-100 md:hidden">{rows.map((p) => <ParticipantCard key={p.id} participant={p} onScore={() => onScore(p)} />)}</div>{!rows.length ? <Empty title={view === "top9" ? "No Tier A priority yet" : "No participants yet"} body={view === "top9" ? "Only attended Tier A participants qualify; lower tiers are never promoted to fill nine slots." : "Add existing leads to begin scoring."} /> : null}</section>
  </div>;
}

function ParticipantRow({ participant: p, onScore, mutate, refresh }: { participant: Participant; onScore: () => void; mutate: (body: Record<string, unknown>) => Promise<Record<string, unknown> | null>; refresh: () => void }) {
  return <tr className="hover:bg-slate-50"><td className="px-3 py-3 font-black">{p.rank ? `#${p.rank}` : "—"}</td><td className="px-3 py-3"><p className="font-black text-slate-900">{p.lead_name}</p><p className="text-xs text-slate-500">{p.business || p.mobile}</p></td><td className="px-3 py-3">{p.observer || "—"}</td><td className="px-3 py-3">{p.pre_score ?? "—"}</td><td className="px-3 py-3">{p.session_score ?? "—"}</td><td className="px-3 py-3 text-base font-black">{p.total_score ?? "—"}</td><td className="px-3 py-3">{String(p.instant_signal || "-")}</td><td className="px-3 py-3"><Tier tier={p.calculated_tier} /></td><td className="px-3 py-3">{p.meeting_id ? <span className="text-xs font-black text-emerald-700">Booked</span> : p.meetingPriority === "TOP_9" ? <MeetingButton participant={p} mutate={mutate} refresh={refresh} /> : "—"}</td><td className="px-3 py-3"><button className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-black text-white" onClick={onScore} type="button">{p.calculated_tier ? "Update" : "Score"}</button></td></tr>;
}

function ParticipantCard({ participant: p, onScore }: { participant: Participant; onScore: () => void }) { return <button className="flex w-full items-center gap-3 p-4 text-left" onClick={onScore} type="button"><span className={`grid size-11 shrink-0 place-items-center rounded-xl font-black ${p.meetingPriority === "TOP_9" ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-600"}`}>{p.rank ? `#${p.rank}` : "—"}</span><span className="min-w-0 flex-1"><span className="block truncate font-black text-slate-950">{p.lead_name}</span><span className="mt-1 block text-xs font-bold text-slate-500">Pre {p.pre_score ?? "—"} · Session {p.session_score ?? "—"}</span></span><span className="text-right"><span className="block text-xl font-black">{p.total_score ?? "—"}</span><Tier tier={p.calculated_tier} /></span></button>; }

function ScorecardSheet({ participant, busy, onClose, onSaved, mutate }: { participant: Participant; busy: boolean; onClose: () => void; onSaved: () => void; mutate: (body: Record<string, unknown>) => Promise<Record<string, unknown> | null> }) {
  const [answers, setAnswers] = useState<ScorecardInput>(() => readAnswers(participant)); const [notes, setNotes] = useState(String(participant.notes || ""));
  const preview = useMemo(() => calculateSessionScorecard(answers), [answers]);
  const set = <K extends keyof ScorecardInput>(key: K, value: ScorecardInput[K]) => setAnswers((current) => ({ ...current, [key]: value }));
  const behaviours: Array<[keyof ScorecardInput,string,number]> = [["attended","Aaya?",0],["onTime","Time pe?",5],["notesTaken","Notes liye?",8],["askedQuestion","Question?",10],["stayedUntilEnd","End tak?",7],["cameWithSomeone","Saath aaya?",8],["metPersonally","KHUD mila?",12]];
  return <Sheet onClose={onClose} title={participant.lead_name}><div className="space-y-5 p-4 sm:p-5"><section><SectionTitle text="Pre qualification" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><Option label="Turnover" config={SCORECARD_CONFIG.turnover} value={answers.turnoverOption} onChange={(v) => set("turnoverOption", v as ScorecardInput["turnoverOption"])} /><Option label="Team size" config={SCORECARD_CONFIG.teamSize} value={answers.teamSizeOption} onChange={(v) => set("teamSizeOption", v as ScorecardInput["teamSizeOption"])} /><Option label="Time freedom" config={SCORECARD_CONFIG.timeFreedom} value={answers.timeFreedomOption} onChange={(v) => set("timeFreedomOption", v as ScorecardInput["timeFreedomOption"])} /><Option label="Vintage" config={SCORECARD_CONFIG.vintage} value={answers.vintageOption} onChange={(v) => set("vintageOption", v as ScorecardInput["vintageOption"])} /></div></section><section><SectionTitle text="Session observation" /><div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200">{behaviours.map(([key,label,marks]) => <div className="flex items-center justify-between gap-3 p-3" key={key}><div><p className="text-sm font-black">{label}</p>{marks ? <p className="text-xs font-bold text-slate-400">{marks} marks</p> : <p className="text-xs font-bold text-slate-400">Attendance gate</p>}</div><YesNo value={Boolean(answers[key])} onChange={(v) => set(key, v as never)} /></div>)}</div></section><section><SectionTitle text="Instant signal" /><div className="mt-3 grid grid-cols-3 gap-2">{(["-","A","C"] as InstantSignal[]).map((value) => <button className={`min-h-11 rounded-xl border text-sm font-black ${answers.instantSignal === value ? value === "A" ? "border-emerald-600 bg-emerald-600 text-white" : value === "C" ? "border-rose-600 bg-rose-600 text-white" : "border-slate-900 bg-slate-900 text-white" : "border-slate-200 bg-white text-slate-600"}`} key={value} onClick={() => set("instantSignal", value)} type="button">{value}</button>)}</div><textarea className={`${inputClass} mt-3 min-h-20`} onChange={(e) => setNotes(e.target.value)} placeholder="Observer notes" value={notes} /></section><ScoreResult answers={answers} preview={preview} /><button className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-3.5 text-sm font-black text-white disabled:opacity-50" disabled={busy} onClick={async () => { const data = await mutate({ action: "save_scorecard", participantId: participant.id, answers, notes, observer: participant.observer || "Admin" }); if (data) onSaved(); }} type="button"><Save className="size-4" />{busy ? "Saving…" : "Save scorecard"}</button></div></Sheet>;
}

function ScoreResult({ answers, preview }: { answers: ScorecardInput; preview: ReturnType<typeof calculateSessionScorecard> }) { const rows = [["Turnover",preview.turnoverScore,15],["Team Size",preview.teamSizeScore,10],["Time Freedom",preview.timeFreedomScore,15],["Vintage",preview.vintageScore,10],["Time pe",preview.behaviourBreakdown.onTime,5],["Notes",preview.behaviourBreakdown.notesTaken,8],["Question",preview.behaviourBreakdown.askedQuestion,10],["End tak",preview.behaviourBreakdown.stayedUntilEnd,7],["Saath aaya",preview.behaviourBreakdown.cameWithSomeone,8],["KHUD mila",preview.behaviourBreakdown.metPersonally,12]] as const; return <section className="rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-slate-400">Live result</p><p className="mt-1 text-3xl font-black">{preview.totalScore}/100</p></div><span className="rounded-lg bg-white px-3 py-2 text-sm font-black text-slate-950">{preview.calculatedTier === "NOT_ATTENDED" ? "Not attended" : `Tier ${preview.calculatedTier}`}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/10 p-3"><p className="text-xs font-bold text-slate-400">PRE SCORE</p><p className="text-xl font-black">{preview.preScore}/50</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-xs font-bold text-slate-400">SESSION SCORE</p><p className="text-xl font-black">{preview.sessionScore}/50</p></div></div><details className="mt-3"><summary className="cursor-pointer text-xs font-black text-slate-300">View exact breakdown</summary><div className="mt-2 divide-y divide-white/10">{rows.map(([label,value,max]) => <div className="flex justify-between py-1.5 text-xs" key={label}><span>{label}</span><strong>{value}/{max}</strong></div>)}</div></details>{!answers.attended ? <p className="mt-3 text-xs font-bold text-amber-300">Aaya is No, so the session score is gated to 0.</p> : null}</section>; }

function CreateSession({ busy, onClose, onSave }: { busy: boolean; onClose: () => void; onSave: (body: Record<string, unknown>) => void }) { const [form,setForm]=useState({name:"Business Growth Session",sessionDate:new Date().toISOString().slice(0,10),startTime:"",endTime:"",location:"",capacity:"100"}); return <Sheet title="Create session" onClose={onClose}><form className="space-y-4 p-5" onSubmit={(e) => { e.preventDefault(); onSave(form); }}>{Object.entries({name:"Session name",sessionDate:"Date",startTime:"Start time",endTime:"End time",location:"Location",capacity:"Capacity"}).map(([key,label]) => <label className="block text-sm font-black" key={key}>{label}<input className={`${inputClass} mt-1.5`} required={["name","sessionDate"].includes(key)} type={key === "sessionDate" ? "date" : key.includes("Time") ? "time" : key === "capacity" ? "number" : "text"} value={form[key as keyof typeof form]} onChange={(e) => setForm({...form,[key]:e.target.value})} /></label>)}<button className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-black text-white" disabled={busy} type="submit">Create session</button></form></Sheet>; }
function AddParticipant({ leads, busy, onClose, onSave }: { leads: Lead[]; busy: boolean; onClose: () => void; onSave: (lead: Lead) => void }) { const [search,setSearch]=useState(""); const matches=leads.filter((l) => [l.name,l.mobile,l.email,l.interest].some((v) => String(v||"").toLowerCase().includes(search.toLowerCase()))).slice(0,30); return <Sheet title="Add lead to session" onClose={onClose}><div className="p-5"><label className="relative block"><Search className="absolute left-3 top-3.5 size-4 text-slate-400" /><input autoFocus className={`${inputClass} pl-10`} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, phone, email or business" value={search} /></label><div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200">{matches.map((lead) => <button className="flex w-full items-center gap-3 p-3 text-left hover:bg-slate-50" disabled={busy} key={lead.id} onClick={() => onSave(lead)} type="button"><span className="grid size-10 place-items-center rounded-lg bg-slate-100"><Plus className="size-4" /></span><span><span className="block text-sm font-black">{lead.name}</span><span className="text-xs font-bold text-slate-500">{lead.mobile} · {lead.interest || "No business set"}</span></span></button>)}{!matches.length ? <p className="p-5 text-center text-sm font-bold text-slate-500">No matching leads.</p> : null}</div></div></Sheet>; }
function MeetingButton({ participant, mutate, refresh }: { participant: Participant; mutate: (body: Record<string, unknown>) => Promise<Record<string, unknown> | null>; refresh: () => void }) { const [open,setOpen]=useState(false); const [meetingAt,setMeetingAt]=useState(""); const [owner,setOwner]=useState(participant.observer || ""); if (!open) return <button className="rounded-lg bg-amber-400 px-2.5 py-2 text-xs font-black text-slate-950" onClick={() => setOpen(true)} type="button">Book</button>; return <div className="min-w-48 space-y-1.5"><input className={inputClass} onChange={(e) => setMeetingAt(e.target.value)} type="datetime-local" value={meetingAt} /><input className={inputClass} onChange={(e) => setOwner(e.target.value)} placeholder="Owner" value={owner} /><button className="w-full rounded-lg bg-emerald-600 px-2 py-2 text-xs font-black text-white" onClick={async () => { if (await mutate({action:"book_meeting",participantId:participant.id,meetingAt,owner})) refresh(); }} type="button">Confirm</button></div>; }

function Option({ label, config, value, onChange }: { label: string; config: Record<string,{label:string;score:number}>; value: string; onChange: (value:string) => void }) { return <label className="text-sm font-black">{label}<select className={`${inputClass} mt-1.5`} onChange={(e) => onChange(e.target.value)} value={value}>{Object.entries(config).map(([key,item]) => <option key={key} value={key}>{item.label} · {item.score}</option>)}</select></label>; }
function YesNo({ value, onChange }: { value: boolean; onChange: (value:boolean) => void }) { return <div className="grid grid-cols-2 overflow-hidden rounded-lg border border-slate-200"><button className={`min-h-10 px-3 text-xs font-black ${value ? "bg-emerald-600 text-white" : "bg-white text-slate-500"}`} onClick={() => onChange(true)} type="button">YES</button><button className={`min-h-10 px-3 text-xs font-black ${!value ? "bg-rose-600 text-white" : "bg-white text-slate-500"}`} onClick={() => onChange(false)} type="button">NO</button></div>; }
function Tier({ tier }: { tier?: string }) { if (!tier) return <span className="text-xs font-bold text-slate-400">Not scored</span>; const tone=tier === "A" ? "bg-emerald-50 text-emerald-700" : tier === "B" ? "bg-amber-50 text-amber-700" : tier === "C" ? "bg-rose-50 text-rose-700" : "bg-slate-100 text-slate-600"; return <span className={`inline-flex rounded-lg px-2 py-1 text-[11px] font-black ${tone}`}>{tier === "NOT_ATTENDED" ? "Not attended" : `Tier ${tier}`}</span>; }
function Sheet({ title, onClose, children }: { title:string; onClose:()=>void; children:React.ReactNode }) { return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/45"><button aria-label="Close" className="min-w-0 flex-1" onClick={onClose} type="button" /><aside className="h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white p-4"><h2 className="text-xl font-black">{title}</h2><button className="grid size-10 place-items-center rounded-lg border border-slate-200" onClick={onClose} type="button"><X className="size-4" /></button></header>{children}</aside></div>; }
function SectionTitle({ text }: { text:string }) { return <h3 className="text-xs font-black uppercase tracking-[.12em] text-slate-500">{text}</h3>; }
function Empty({ title, body }: { title:string; body:string }) { return <div className="grid min-h-56 place-items-center p-6 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-xl bg-slate-100 text-slate-500"><UsersRound className="size-5" /></span><p className="mt-3 font-black">{title}</p><p className="mt-1 max-w-sm text-sm font-semibold text-slate-500">{body}</p></div></div>; }
function formatDate(value:string) { return new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}); }
function readAnswers(p: Participant): ScorecardInput { return { turnoverOption: String(p.turnover_option || initialAnswers.turnoverOption) as ScorecardInput["turnoverOption"], teamSizeOption: String(p.team_size_option || initialAnswers.teamSizeOption) as ScorecardInput["teamSizeOption"], timeFreedomOption: String(p.time_freedom_option || initialAnswers.timeFreedomOption) as ScorecardInput["timeFreedomOption"], vintageOption: String(p.vintage_option || initialAnswers.vintageOption) as ScorecardInput["vintageOption"], attended: Boolean(p.attended), onTime: Boolean(p.on_time), notesTaken: Boolean(p.notes_taken), askedQuestion: Boolean(p.asked_question), stayedUntilEnd: Boolean(p.stayed_until_end), cameWithSomeone: Boolean(p.came_with_someone), metPersonally: Boolean(p.met_personally), instantSignal: String(p.instant_signal || "-") as InstantSignal }; }
