"use client";

import { AdminPlatformShell } from "@/components/admin-platform-shell";
import { createLeadActivity, nextPendingFollowUp, normalizeLead, normalizeLeadMobile } from "@/lib/lead-utils";
import { taskBucket } from "@/lib/crm-workflow";
import { hydrateLiveState, LIVE_STATE_STORAGE_KEYS, readLocalArray, saveLiveState } from "@/lib/live-state";
import type { Lead, LeadFollowUp } from "@/lib/types";
import { CalendarClock, Check, Clock3, Phone, Search, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Bucket = "today"|"overdue"|"upcoming"|"done";
type TaskRow = { lead: Lead; task: LeadFollowUp };

export default function FollowUpsPage(){
  const [leads,setLeads]=useState<Lead[]>([]); const [bucket,setBucket]=useState<Bucket>("today"); const [search,setSearch]=useState("");
  useEffect(()=>{const load=()=>setLeads(readLocalArray<unknown>(LIVE_STATE_STORAGE_KEYS.leads).map(normalizeLead));load();void hydrateLiveState().then(load)},[]);
  const all=useMemo(()=>leads.filter((lead)=>!lead.blocked).flatMap((lead)=>(lead.followUps??[]).map((task)=>({lead,task}))),[leads]);
  const rows=all.filter(({lead,task})=>taskBucket(task)===bucket&&[lead.name,lead.mobile,lead.assignedTo,task.note,task.type].some((v)=>String(v||"").toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>new Date(a.task.dueAt).getTime()-new Date(b.task.dueAt).getTime());
  const counts={today:all.filter((x)=>taskBucket(x.task)==="today").length,overdue:all.filter((x)=>taskBucket(x.task)==="overdue").length,upcoming:all.filter((x)=>taskBucket(x.task)==="upcoming").length,done:all.filter((x)=>taskBucket(x.task)==="done").length};
  async function complete(row:TaskRow){const now=new Date().toISOString();const next=leads.map((lead)=>{if(lead.id!==row.lead.id)return lead;const followUps=(lead.followUps??[]).map((item)=>item.id===row.task.id?{...item,completed:true,completedAt:now}:item);return normalizeLead({...lead,followUps,nextFollowUp:nextPendingFollowUp(followUps)?.dueAt??"",lastActivityAt:now,activities:[createLeadActivity("follow_up",`${row.task.type} follow-up completed.`),...(lead.activities??[])]})});setLeads(next);await saveLiveState({leads:next})}
  return <AdminPlatformShell activeLabel="Follow-ups" description="One queue for overdue, today, upcoming and completed sales actions." title="Follow-up Center">
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{(["overdue","today","upcoming","done"] as Bucket[]).map((value)=><button className={`rounded-xl border p-4 text-left ${bucket===value?"border-slate-950 bg-slate-950 text-white":"border-slate-200 bg-white text-slate-950"}`} key={value} onClick={()=>setBucket(value)} type="button"><p className={`text-xs font-black uppercase ${bucket===value?"text-slate-300":"text-slate-500"}`}>{value}</p><p className="mt-2 text-3xl font-black">{counts[value]}</p></button>)}</section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><header className="border-b border-slate-200 p-4"><label className="relative block max-w-xl"><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><input className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-3 text-sm font-bold" onChange={(e)=>setSearch(e.target.value)} placeholder="Search lead, owner or task" value={search}/></label></header><div className="divide-y divide-slate-100">{rows.map((row)=><div className="flex flex-wrap items-center gap-3 p-4" key={`${row.lead.id}-${row.task.id}`}><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${bucket==="overdue"?"bg-rose-50 text-rose-700":"bg-slate-100 text-slate-600"}`}><CalendarClock className="size-5"/></span><div className="min-w-48 flex-1"><div className="flex flex-wrap items-center gap-2"><a className="font-black hover:text-emerald-700" href={`/crm/leads/${encodeURIComponent(row.lead.id)}`}>{row.lead.name}</a><span className="rounded-lg bg-slate-100 px-2 py-1 text-[11px] font-black">{row.task.type}</span></div><p className={`mt-1 text-xs font-bold ${bucket==="overdue"?"text-rose-600":"text-slate-500"}`}>{formatDate(row.task.dueAt)} · {row.lead.assignedTo||"Unassigned"}</p>{row.task.note?<p className="mt-1 text-sm font-semibold text-slate-600">{row.task.note}</p>:null}</div><div className="flex gap-2"><a aria-label="Call" className="grid size-10 place-items-center rounded-lg bg-sky-50 text-sky-700" href={`tel:+91${normalizeLeadMobile(row.lead.mobile)}`}><Phone className="size-4"/></a>{!row.task.completed?<button className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-3 text-xs font-black text-white" onClick={()=>void complete(row)} type="button"><Check className="size-4"/>Done</button>:null}</div></div>)}{!rows.length?<div className="grid min-h-64 place-items-center text-center"><div><UsersRound className="mx-auto size-8 text-slate-300"/><p className="mt-3 font-black">No {bucket} tasks</p><p className="mt-1 text-sm font-semibold text-slate-500">Tasks will appear when a next action is scheduled.</p></div></div>:null}</div></section>
  </AdminPlatformShell>
}
function formatDate(value:string){return new Date(value).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true})}
